### ISSUE TITLE
http://api.geetest.com/get.php 这是干什么的

### ISSUE THREAD

**Issue by ghostsf** [JellyBool/geeCaptcha#3]
有用吗？

**Comment by JellyBool** [comment]
这是嵌入 geetest 的 js 的吧。

**Comment by ghostsf** [comment]
重复了，可以去掉。http://static.geetest.com/static/tools/gt.js 会去请求，并引用到。

**Comment by aviggngyv** [comment]
你的包里好像有session_start，这个会和其他包冲突

**Comment by JellyBool** [comment]
可否把你的具体例子和代码看一下？ @aviggngyv

**Comment by aviggngyv** [comment]
我用了这个包https://github.com/opis/session，

写在了框架加载中，昨天在使用你的这个包时，如果判断isFromGTServer 就会执行session_start， 就冲突了，这是我的开源框架https://github.com/hunteryun/HunterPHP

**Comment by JellyBool** [comment]
这个是你用的 session package 跟自身的 php session 冲突了吧。你可以先看这个 https://github.com/GeeTeam/gt-php-sdk/blob/master/lib/class.geetestlib.php

我稍后再升级一下代码。 @aviggngyv

**Comment by aviggngyv** [comment]
呃，我又来了，还发现个小问题：

```
    /**
     * @return bool|mixed|string
     *
     * 判断验证是否成功
     */
    public function success()
    {
        $result = false;

        if(isset($_POST['geetest_challenge'])) {
          $result = $this->success_validate($_POST['geetest_challenge'], $_POST['geetest_validate'], $_POST['geetest_seccode']);
        }

        return $result;
    }
```
好像加上判断更好些，要不别人不点验证直接提交会有notice提示

**Comment by 14r4veek** [comment]
按照你的laravel样例走了一遍，样式加载失败，我的姿势有问题？
